const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

const GET_USER_INFO = 'GET_USER_INFO'

const USER_SIGNUP_REQUEST ='USER_SIGNUP_REQUEST'
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

const USER_SIGNIN_REQUEST ='USER_SIGNIN_REQUEST'
const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'

const GET_USER_INFO_REQUEST ='GET_USER_INFO_REQUEST'
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL'

const UPDATE_USER_INFO_REQUEST ='UPDATE_USER_INFO_REQUEST'
const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL'

export {
    TOGGLE_SIDEBAR,
    GET_USER_INFO,
    
    USER_SIGNUP_REQUEST,
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAIL,

    USER_SIGNIN_REQUEST,
    USER_SIGNIN_SUCCESS,
    USER_SIGNIN_FAIL,

    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESS,
    GET_USER_INFO_FAIL,

    UPDATE_USER_INFO_REQUEST,
    UPDATE_USER_INFO_SUCCESS,
    UPDATE_USER_INFO_FAIL
}